[build]
  command = "pip install -r requirements.txt"

[functions]
  directory = "netlify/functions"
  included_files = [ "core/**", "node/**", "storage/**", "storage/schema.sql" ]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
